api_version = "2025-01"

[[extensions]]
name = "Estimated Delivery Date"
handle = "delivery-date"
type = "theme"

  [[extensions.blocks]]
  template = "blocks/delivery-date.liquid"
  name = "Delivery Date Estimate"
  target = "section"
